add proposal templates
developer-learning/paper-reading pull request #11
Opened 2019-06-24 13:12 UTC by FelixSeptem

添加proposal相关issue模板，后续可丰富issue label来方便管理不同领域的论文review，pr合并上可以采用approver或者lgtm来管理

2019-06-24 13:18 UTC, FelixSeptem commented
@yangwenmai PTAL

2019-06-25 02:43 UTC, yangwenmai requested changes

2019-06-25 02:43 UTC, yangwenmai commented on .github/ISSUE_TEMPLATE/proposal.md
> +* 预计讨论时间: 2019-07-01 20:00:00 (建议至少距离issue踢出日期7天以上，具体间隔可根据author时间安排和论文难度调整)
1. 踢出 -> 提出；
2. 中英文需要有空格间隔；
3. 串讲人需要准备好 PPT；
4. issue label 我们需要事先约定好，并在 issue template 上做备注说明；

2019-06-25 02:49 UTC, FelixSeptem commented on .github/ISSUE_TEMPLATE/proposal.md
> +* 预计讨论时间: 2019-07-01 20:00:00 (建议至少距离issue踢出日期7天以上，具体间隔可根据author时间安排和论文难度调整)
issue label 这种枚举类型慢慢维护吧，格式问题我先改下

2019-06-25 04:15 UTC, yangwenmai approved these changes

2019-06-25 04:15 UTC, merged